# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_T6ow23s328aMKmoQt_VzxhAK5ZtzGY
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import math

# %matplotlib inline

plt.style.use("default")

def circulo():
  eixos = plt.subplot()

  eixos.grid(True)

  eixos.set_aspect(1)
  eixos.add_artist(plt.Circle((0, 0), 1, fill = False))

  eixos.axhline(y = 0, color= 'black')
  eixos.axvline(x = 0, color= 'black')

  sen = 0.5
  cos = 0.866

  eixos.plot([0, 1], [0, sen],  color = 'red', label = 'cateto oposto')
  eixos.plot([0, 0], [0, sen],  color = 'blue', label = 'seno')
  eixos.plot([0, cos], [0, 0],  color = 'green', label = 'cosseno')
  eixos.plot([1, 1], [-1, 1], color = 'black', label = 'tangente geral')
  eixos.plot([1, 1], [0.5, 0], color = 'yellow', label = 'tangente')

  plt.xlim(-1.1, 1.1)
  plt.ylim(-1.1, 1.1)

  plt.title("Círculo Trigonométrico")
  plt.show()

circulo()